
/**
* optimizationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from generator.idl
* Tuesday, December 18, 2018 9:44:01 PM CET
*/

public final class optimizationHolder implements org.omg.CORBA.portable.Streamable
{
  public optimization value = null;

  public optimizationHolder ()
  {
  }

  public optimizationHolder (optimization initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = optimizationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    optimizationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return optimizationHelper.type ();
  }

}
