
/**
* optimization.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from generator.idl
* Tuesday, December 18, 2018 9:44:01 PM CET
*/

public interface optimization extends optimizationOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface optimization
