
/**
* optimizationOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from generator.idl
* Tuesday, December 18, 2018 9:44:01 PM CET
*/

public interface optimizationOperations 
{
  void register (short ip, int timeout, org.omg.CORBA.IntHolder id);
  void hello (int id);
  void best_range (rangeHolder r);
} // interface optimizationOperations
