
/**
* range.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from generator.idl
* Tuesday, December 18, 2018 9:44:01 PM CET
*/

public final class range implements org.omg.CORBA.portable.IDLEntity
{
  public short from = (short)0;
  public short to = (short)0;

  public range ()
  {
  } // ctor

  public range (short _from, short _to)
  {
    from = _from;
    to = _to;
  } // ctor

} // class range
